title: Jahn Star Games
author: Halil Emre Yildiz
description: The Next Generation of High-Fidelity Mobile Games. My Journey Sebastia.
theme: jekyll-theme-cayman
github:
 is_project_page: false
 darkmode: true
