title: Jahn Star Games
author: Halil Emre Yildiz
description: The Next Generation of High-Fidelity Mobile Games. <br/> [Play My Journey Sebastia](https://play.google.com/store/apps/details?id=com.JahnStarGames.MyJourneySebastia)
theme: jekyll-theme-cayman
github:
 is_project_page: false
 darkmode: true
