title: Jahn Star Games
description: The Next Generation of High-Fidelity Mobile Games. My Journey: Sebastia. Jahn Star Games.
author: Halil Emre Yildiz
theme: jekyll-theme-cayman
github:
 is_project_page: false
 buttons: 
 github_hide: true 
 darkmode: true
